"""add campaigns and link posts to campaigns

Revision ID: 001331f352db
Revises: cbc7de9c4a14
Create Date: 2026-09-24 08:57:25.198512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001331f352db'
down_revision: Union[str, Sequence[str], None] = 'cbc7de9c4a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
