"""add campaign_id to posts

Revision ID: 109e93ae65f9
Revises: 001331f352db
Create Date: 2026-09-24 09:05:55.374165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109e93ae65f9'
down_revision: Union[str, Sequence[str], None] = '001331f352db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_posts_campaign_id'), 'posts', ['campaign_id'], unique=False)
    op.create_foreign_key(None, 'posts', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_campaign_id'), table_name='posts')
    op.drop_column('posts', 'campaign_id')
    # ### end Alembic commands ###
