"""add social account to publishing logs

Revision ID: 58e5bfb3e71e
Revises: a4707483309a
Create Date: 2026-09-26 15:07:51.520999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e5bfb3e71e'
down_revision: Union[str, Sequence[str], None] = 'a4707483309a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publishing_logs', sa.Column('social_account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_publishing_logs_social_account_id'), 'publishing_logs', ['social_account_id'], unique=False)
    op.create_foreign_key(None, 'publishing_logs', 'social_accounts', ['social_account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publishing_logs', type_='foreignkey')
    op.drop_index(op.f('ix_publishing_logs_social_account_id'), table_name='publishing_logs')
    op.drop_column('publishing_logs', 'social_account_id')
    # ### end Alembic commands ###
