"""add recurring post fields

Revision ID: a4652dae5a63
Revises: f7dbe4922853
Create Date: 2026-09-24 04:25:33.594335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4652dae5a63'
down_revision: Union[str, Sequence[str], None] = 'f7dbe4922853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'posts',
    sa.Column(
        'is_recurring',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false'),
    ),
)
    op.add_column('posts', sa.Column('recurrence_type', sa.String(length=50), nullable=True))
    op.add_column('posts', sa.Column('recurrence_end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'recurrence_end_date')
    op.drop_column('posts', 'recurrence_type')
    op.drop_column('posts', 'is_recurring')
    # ### end Alembic commands ###
