"""add engagement metrics to publishing logs

Revision ID: dedafbdd7b44
Revises: 58e5bfb3e71e
Create Date: 2026-09-28 22:49:22.114446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dedafbdd7b44'
down_revision: Union[str, Sequence[str], None] = '58e5bfb3e71e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publishing_logs', sa.Column('platform_media_id', sa.String(length=255), nullable=True))
    op.add_column('publishing_logs', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('publishing_logs', sa.Column('comments', sa.Integer(), nullable=True))
    op.add_column('publishing_logs', sa.Column('shares', sa.Integer(), nullable=True))
    op.add_column('publishing_logs', sa.Column('reach', sa.Integer(), nullable=True))
    op.add_column('publishing_logs', sa.Column('views', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_publishing_logs_platform_media_id'), 'publishing_logs', ['platform_media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publishing_logs_platform_media_id'), table_name='publishing_logs')
    op.drop_column('publishing_logs', 'views')
    op.drop_column('publishing_logs', 'reach')
    op.drop_column('publishing_logs', 'shares')
    op.drop_column('publishing_logs', 'comments')
    op.drop_column('publishing_logs', 'likes')
    op.drop_column('publishing_logs', 'platform_media_id')
    # ### end Alembic commands ###
