"""create publishing logs table

Revision ID: deee578c6093
Revises: a4652dae5a63
Create Date: 2026-09-24 04:50:31.483443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deee578c6093'
down_revision: Union[str, Sequence[str], None] = 'a4652dae5a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_logs_id'), 'publishing_logs', ['id'], unique=False)
    op.create_index(op.f('ix_publishing_logs_post_id'), 'publishing_logs', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publishing_logs_post_id'), table_name='publishing_logs')
    op.drop_index(op.f('ix_publishing_logs_id'), table_name='publishing_logs')
    op.drop_table('publishing_logs')
    # ### end Alembic commands ###
